//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoIt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attempt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Attempt()
        {
            this.Comments = new HashSet<Comment>();
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int AttemptId { get; set; }
        public int Budget { get; set; }
        public int DaysToComplete { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string Description { get; set; }
        public int Status { get; set; }
        public int AuthorId { get; set; }
        public int ServiceId { get; set; }
    
        public virtual User User { get; set; }
        public virtual Service Service { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
