//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoIt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int CommentId { get; set; }
        public string Comment1 { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int AuthorId { get; set; }
        public int AttemptId { get; set; }
    
        public virtual Attempt Attempt { get; set; }
        public virtual User User { get; set; }
    }
}
