//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoIt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TransactionId { get; set; }
        public int Status { get; set; }
        public int CustomerId { get; set; }
        public int ProviderId { get; set; }
        public int AttemptId { get; set; }
    
        public virtual Attempt Attempt { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
