CREATE DATABASE DoIt
USE DoIt

CREATE TABLE Users(
	UserId INT IDENTITY(1,1) PRIMARY KEY,
	Name VARCHAR(50) NOT NULL,
	PhoneNumber VARCHAR (10) NOT NULL,
	Email VARCHAR(50) NOT NULL,
	Password VARCHAR(32) NOT NULL,
	Address VARCHAR(100) NOT NULL,
	ProviderScore DECIMAL(3,2) DEFAULT 0 NOT NULL,
	CustomerScore DECIMAL(3,2) DEFAULT 0 NOT NULL,
	ProviderDescription VARCHAR(300),
	ProfilePicture VARCHAR(200)
);

CREATE TABLE Services(
	ServiceId INT IDENTITY(1,1) PRIMARY KEY,
	Title VARCHAR(50) NOT NULL,
	Description VARCHAR(500),
	MinBudget INT NOT NULL,
	MaxBudget INT NOT NULL,
	CreationDate DATETIME NOT NULL,
	ExpirationDate DATETIME NOT NULL,
	Status INT NOT NULL,

	AuthorId INT FOREIGN KEY REFERENCES Users(UserId)
);

CREATE TABLE Attempts(
	AttemptId INT IDENTITY(1,1) PRIMARY KEY,
	Budget INT NOT NULL,
	DaysToComplete INT NOT NULL,
	CreationDate DATETIME NOT NULL,
	Description VARCHAR(500) NOT NULL,
	Status INT NOT NULL,

	AuthorId INT FOREIGN KEY REFERENCES Users(UserId) NOT NULL,
	ServiceId INT FOREIGN KEY REFERENCES Services(ServiceId) NOT NULL
);

CREATE TABLE Comments(
	CommentId INT IDENTITY(1,1) PRIMARY KEY,
	Comment VARCHAR(300) NOT NULL,
	CreationDate DATETIME NOT NULL,

	AuthorId INT FOREIGN KEY REFERENCES Users(UserId) NOT NULL,
	AttemptId INT FOREIGN KEY REFERENCES Attempts(AttemptId) NOT NULL
);

CREATE TABLE Transactions(
	TransactionId INT IDENTITY(1,1) PRIMARY KEY,
	Status INT NOT NULL,

	CustomerId INT FOREIGN KEY REFERENCES Users(UserId) NOT NULL,
	ProviderId INT FOREIGN KEY REFERENCES Users(UserId) NOT NULL,
	AttemptId INT FOREIGN KEY REFERENCES Attempts(AttemptId) NOT NULL,
);